"""Page 8 — Export model as LaTeX, JSON, Word/Excel reports."""

from __future__ import annotations

import os

os.environ["JAX_PLATFORMS"] = "cpu"

import json

import streamlit as st

from jaxsr.app.components import study_status_sidebar
from jaxsr.app.state import get_study, get_study_path, require_fitted, require_study

# ---------------------------------------------------------------------------
study_status_sidebar(get_study())
study = require_study()
require_fitted(study)

model = study.model

# ---------------------------------------------------------------------------
st.header("Export")

# ---------------------------------------------------------------------------
# LaTeX
# ---------------------------------------------------------------------------
st.subheader("LaTeX Equation")
try:
    latex_str = model.to_latex()
    st.latex(latex_str)

    # Download as .tex file
    tex_content = f"% Generated by JAXSR\n% Study: {study.name}\n${latex_str}$\n"
    st.download_button(
        "Download .tex",
        data=tex_content,
        file_name=f"{study.name}_model.tex",
        mime="text/x-tex",
    )
except Exception as e:
    st.warning(f"Could not generate LaTeX: {e}")

# ---------------------------------------------------------------------------
# SymPy expression
# ---------------------------------------------------------------------------
st.subheader("SymPy Expression")
try:
    sympy_expr = model.to_sympy()
    st.code(str(sympy_expr), language="python")
except Exception as e:
    st.warning(f"Could not generate SymPy expression: {e}")

# ---------------------------------------------------------------------------
# Model JSON
# ---------------------------------------------------------------------------
st.subheader("Model JSON")
try:
    # Serialize model state to JSON-compatible dict
    model_data = {
        "expression": model.expression_,
        "coefficients": [float(c) for c in model.coefficients_],
        "features": model.selected_features_,
        "metrics": {k: float(v) for k, v in model.metrics_.items()},
    }
    json_str = json.dumps(model_data, indent=2)
    st.code(json_str, language="json")

    st.download_button(
        "Download JSON",
        data=json_str,
        file_name=f"{study.name}_model.json",
        mime="application/json",
    )
except Exception as e:
    st.warning(f"Could not serialize model: {e}")

# ---------------------------------------------------------------------------
# Study .jaxsr file
# ---------------------------------------------------------------------------
st.subheader("Study File")
study_path = get_study_path()
if study_path:
    try:
        with open(study_path, "rb") as f:
            study_data = f.read()
        st.download_button(
            "Download .jaxsr",
            data=study_data,
            file_name=f"{study.name}.jaxsr",
            mime="application/octet-stream",
        )
    except FileNotFoundError:
        st.info("Study file not found on disk. Save it first from Setup.")
else:
    st.info("No study file path set.")

# ---------------------------------------------------------------------------
# Excel / Word reports
# ---------------------------------------------------------------------------
st.subheader("Reports")
col1, col2 = st.columns(2)

with col1:
    st.markdown("**Excel Report**")
    try:
        import tempfile
        from pathlib import Path

        from jaxsr.excel import add_report_sheets

        if st.button("Generate Excel Report", key="gen_xlsx"):
            with tempfile.NamedTemporaryFile(suffix=".xlsx", delete=False) as tmp:
                add_report_sheets(study, tmp.name)
                tmp_path = tmp.name

            with open(tmp_path, "rb") as f:
                xlsx_data = f.read()

            st.download_button(
                "Download Excel Report",
                data=xlsx_data,
                file_name=f"{study.name}_report.xlsx",
                mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            )
            Path(tmp_path).unlink(missing_ok=True)
    except ImportError:
        st.info("Install `openpyxl` and `xlsxwriter` for Excel reports: `pip install jaxsr[excel]`")

with col2:
    st.markdown("**Word Report**")
    try:
        import tempfile
        from pathlib import Path

        from jaxsr.reporting import generate_word_report  # noqa: F401

        if st.button("Generate Word Report", key="gen_docx"):
            with tempfile.NamedTemporaryFile(suffix=".docx", delete=False) as tmp:
                generate_word_report(study, tmp.name)
                tmp_path = tmp.name

            with open(tmp_path, "rb") as f:
                docx_data = f.read()

            st.download_button(
                "Download Word Report",
                data=docx_data,
                file_name=f"{study.name}_report.docx",
                mime="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            )
            Path(tmp_path).unlink(missing_ok=True)
    except ImportError:
        st.info("Install `python-docx` for Word reports: `pip install jaxsr[reports]`")

# ---------------------------------------------------------------------------
# Python code snippet
# ---------------------------------------------------------------------------
st.markdown("---")
st.subheader("Python Code Snippet")

code_snippet = f"""import numpy as np
from jaxsr import DOEStudy

# Load the study
study = DOEStudy.load("{study.name}.jaxsr")
model = study.model

# Make predictions
X_new = np.array([[...]])  # your new data
y_pred = model.predict(X_new)

# Get prediction intervals
y_pred, lower, upper = model.predict_interval(X_new, alpha=0.05)

# Export as a pure-Python callable (no JAX needed)
predict_fn = model.to_callable()
y_pred = predict_fn(X_new)
"""

st.code(code_snippet, language="python")
